#!/bin/bash

export HELPER_DIR="$HOME/bin"

export JAVA_VERSION="java-6-jre/jre"
export MAKE_VERSION="3.82"
export TOOL_DIR="$HOME/bin/mydroid-build"
export PYTHON_VERSION="2.7"

export SOURCE_DIR="/home/$USER/android_4.1.2"

source $HELPER_DIR/startup

